Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: cloudreve
    SupplierDeployMetadata:
      ArtifactRelation:
        'centos_7_9_x64_20G_alibase_20240403.vhd':
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: ${Artifact.EcsImage.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - cn-qingdao
          - cn-beijing
          - cn-zhangjiakou
          - cn-huhehaote
          - cn-wulanchabu
          - cn-hangzhou
          - cn-shanghai
          - cn-shenzhen
          - cn-chengdu
          - cn-heyuan
          - cn-guangzhou
          - cn-hongkong
          - ap-northeast-1
          - ap-southeast-1
          - ap-southeast-3
          - ap-southeast-5
          - ap-southeast-6
          - us-east-1
          - us-west-1
          - eu-west-1
          - eu-central-1
          - me-east-1
          - me-central-1
          - cn-nanjing
          - cn-fuzhou
          - ap-southeast-7
          - ap-northeast-2
          - cn-wuhan-lr
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: cloudreve deploy
    Image: 'resources/icons/service_logo.png'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: cloudreve
    Description: cloudreve
    ArtifactProperty:
      RegionId: ${ImageBuilder.EcsImage.RegionId}
      ImageId: ${ImageBuilder.EcsImage.SourceImageId}
    SupportRegionIds:
      - cn-qingdao
      - cn-beijing
      - cn-zhangjiakou
      - cn-huhehaote
      - cn-wulanchabu
      - cn-hangzhou
      - cn-shanghai
      - cn-shenzhen
      - cn-chengdu
      - cn-heyuan
      - cn-guangzhou
      - cn-hongkong
      - ap-northeast-1
      - ap-southeast-1
      - ap-southeast-3
      - ap-southeast-5
      - ap-southeast-6
      - us-east-1
      - us-west-1
      - eu-west-1
      - eu-central-1
      - me-east-1
      - me-central-1
      - cn-nanjing
      - cn-fuzhou
      - ap-southeast-7
      - ap-northeast-2
      - cn-wuhan-lr
ImageBuilder:
  EcsImage:
    RegionId: ap-southeast-1
    SourceImageId: aliyun_3_x64_20G_alibase_20240819.vhd
    SystemDiskSize: 20
    InstanceType: ecs.c6.large
    InternetMaxBandwidthOut: 10
    CommandType: RunShellScript
    Timeout: 10800
    Tags: [ ]
    CommandContent: |-
        #!/bin/bash
        wget -q https://github.com/cloudreve/Cloudreve/releases/download/3.8.3/cloudreve_3.8.3_linux_amd64.tar.gz
        tar -zxvf cloudreve_3.8.3_linux_amd64.tar.gz && rm -f cloudreve_3.8.3_linux_amd64.tar.gz
        chmod +x /root/cloudreve

        cat > /root/start_cloudreve.sh <<'EOF'
        #!/bin/bash
        /root/cloudreve > /root/start.log 2>&1 &
        while true; do
            if [[ -f /root/credentials.txt ]]; then
                break
            elif [[ -f /root/start.log ]]; then
                admin_user=$(grep -oP '(?<=Admin user name: ).*' /root/start.log)
                admin_pass=$(grep -oP '(?<=Admin password: ).*' /root/start.log)

                if [[ -n "$admin_user" && -n "$admin_pass" ]]; then
                    #/root/cloudreve --database-script ResetAdminPassword >> /root/start.log 2>&1
                    #db_pass=$(grep -oP '(?<=Initial admin user password changed to:).*' /root/start.log)
                    echo "cloudreve_username = $admin_user" > /root/credentials.txt
                    echo "cloudreve_password = $admin_pass" >> /root/credentials.txt
                    #echo "mariadb_password = $db_pass" >> /root/credentials.txt
                    break
                fi
            else
                echo "日志文件尚未生成，继续等待..."
            fi
            sleep 5
        done

        /root/cloudreve > /root/start.log 2>&1

        EOF

        chmod +x /root/start_cloudreve.sh

        cat > /etc/systemd/system/cloudreve.service <<EOF
        [Unit]
        Description=Cloudreve
        Documentation=https://docs.cloudreve.org
        After=network.target
        After=mysqld.service
        Wants=network.target

        [Service]
        WorkingDirectory=/root
        ExecStart=/root/start_cloudreve.sh
        EOF

        systemctl daemon-reload
        systemctl enable cloudreve
        systemctl start cloudreve

        ARGUS_VERSION=3.5.7 /bin/bash -c "$(curl -sS https://cms-agent-ap-southeast-1.oss-ap-southeast-1-internal.aliyuncs.com/Argus/agent_install_ecs-1.7.sh)" 2>&1

        # 关闭基础镜像非必要服务，降低基础服务资源占用
        systemctl stop systemd-resolved.service
        systemctl disable systemd-resolved.service
        systemctl stop rpcbind.socket
        systemctl stop rpcbind.service
        systemctl disable rpcbind.service
        systemctl disable rpcbind.socket


        function clean_log(){
            rm -fv /usr/local/aegis/aegis_update/data/data.[0-9]
            rm -fv /usr/local/aegis/aegis_client/aegis_*/data/data.[0-9]

            rm -fv /usr/local/aegis/globalcfg/domaincfg.ini
            rm -fv /opt/aegis/globalcfg/domaincfg.ini

            rm -rf /var/log/anaconda/*
            rm -rf /var/log/ecsgo.log*
            rm -rf /var/log/cron-*
            rm -rf /var/log/btmp-*
            rm -rf /var/log/maillog-*
            rm -rf /var/log/messages-*
            rm -rf /var/log/secure-*
            rm -rf /var/log/spooler-*
            rm -rf /var/log/yum.log-*
            rm -rf /var/log/boot.log-*
            rm -rf /var/log/anaconda/*
            rm -rf /var/log/sa/*
            rm -rf /var/log/conman*

            for i in $(find /var/log/ -type f); do > $i; done

            rm -rfv /var/lib/apt/lists/*
            rm -rfv /var/lib/yum/history/*
            rm -rfv /var/lib/dnf/history*
            rm -rfv /var/lib/dhclient/*
            rm -rfv /var/lib/dhcp/*
            rm -rfv /var/lib/aliyun_init/*
            rm -rfv /var/lib/cloud/*

            rm -rfv  /usr/local/share/aliyun-assist/*/log/*

            rm -rfv /etc/ssh/sshd_config.d/*

            rm -rf /tmp/*
            rm -f /root/{.bash_history,.viminfo,*.cfg,*.log*}
            rm -rf /root/script

            sed -i "/iZ*Z/d" /etc/hosts
            sed -i "/AliYun/d" /etc/hosts
            sed -i "/Aliyun/d" /etc/hosts
            sed -i "/debug/d" /etc/hosts

            # Clean up useless nameservers to prevent cloudinit local domain name resolution timeout
            sed -i '/100.100.2.136\|100.100.2.138/!d' $(realpath /etc/resolv.conf)

            [ -d /etc/NetworkManager/system-connections ] && rm -fv /etc/NetworkManager/system-connections/*.nmconnection

            if [[ ! -L /etc/udev/rules.d/70-persistent-net.rules ]];then
                rm -rfv /etc/udev/rules.d/70-persistent-net.rules
            fi

            sync
            sync
            sync
        }

        function clean_source_cache(){
            if [ `which zypper` ]; then
                zypper clean; rm -fv /etc/zypp/repos.d/CUSTOM*
            elif [ `which apt-get` ]; then
                apt-get -q clean; apt-get -q autoclean; apt-get -q -y autoremove;
            elif [ `which yum` ]; then
                yum clean all;
            elif [ `which dnf` ]; then
                dnf clean all;
            elif [ `which pkg` ]; then
                pkg autoremove
            fi
        }

        function clean_cmd_history(){
            for user in $(cut -f1 -d: /etc/passwd); do
                if [ -f /home/$user/.bash_history ]; then
                    > /home/$user/.bash_history
                fi
            done
            > /root/.bash_history
            history -c
            history -w
        }

        function clean_root_passwd(){
            passwd -l root
            sed -i '/PasswordAuthentication/d' /etc/ssh/sshd_config
            echo 'PasswordAuthentication no' >> /etc/ssh/sshd_config
            sed -i -e 's/root:[^:]*:/root:*:/g' /etc/shadow

            for user in $(cut -f1 -d: /etc/passwd); do
              rm -rf /home/$user/.ssh/*
            done

            rm -f /root/.ssh/*
            rm -f /etc/ssh/ssh_host_*
        }

        clean_source_cache
        clean_log
        clean_cmd_history
        clean_root_passwd